name: check

on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: check uv version
        run: uv --version
